// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RRH_Minigames_API;

#nullable disable

namespace RRHMinigamesAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("RRH_Minigames_API.DbUser", b =>
                {
                    b.Property<string>("GUID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GUID");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("RRH_Minigames_API.PlayerStat", b =>
                {
                    b.Property<string>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DbUserGUID")
                        .HasColumnType("TEXT");

                    b.Property<int>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HighScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid", "Id");

                    b.HasIndex("DbUserGUID");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("RRH_Minigames_API.PlayerStat", b =>
                {
                    b.HasOne("RRH_Minigames_API.DbUser", null)
                        .WithMany("Stats")
                        .HasForeignKey("DbUserGUID");

                    b.HasOne("RRH_Minigames_API.DbUser", "User")
                        .WithMany()
                        .HasForeignKey("Guid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RRH_Minigames_API.DbUser", b =>
                {
                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
